import { Inter } from "next/font/google";
import "./globals.css";
import { ContexProvider } from "@/context/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DAMAS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
            <body className={inter.className}>
            <ContexProvider>{children}</ContexProvider>
            </body>
        </html>
  );
}
